### ISSUE TITLE
Change HTML output

### ISSUE THREAD

**Issue by uidHUB** [iionly/users_online#2]
Hi!

I propose to change the output HTML.
Now:

```
<div class="elgg-body">
  <div class='elgg-avatar elgg-avatar-tiny'>
    <a>...</a>
  </div>
    <div class='elgg-avatar elgg-avatar-tiny'>
    <a>...</a>
  </div>
    <div class='elgg-avatar elgg-avatar-tiny'>
    <a>...</a>
  </div>
</div>
```

I suggest:

```
<ul class="elgg-online-users">
  <li class='elgg-item'>
    <div class='elgg-avatar elgg-avatar-tiny'>
      <a>...</a>
    </div>
  </li>
  <li class='elgg-item'>
    <div class='elgg-avatar elgg-avatar-tiny'>
      <a>...</a>
    </div>
  </li>
  <li class='elgg-item'>
    <div class='elgg-avatar elgg-avatar-tiny'>
      <a>...</a>
    </div>
  </li>
</ul>
```

Like the block "Group members" + allows you to better customize the block.

And will solve the problem with an arrow:

![screenshot from 2016-05-21 20-53-23](https://cloud.githubusercontent.com/assets/12877339/15449967/3bddd0d2-1f96-11e6-990a-f4d26a60ebab.png)

**Comment by iionly** [comment]
I'll try out your suggestion once back from my holiday to see how it works / looks.

**Comment by iionly** [comment]
I've changed the code in version 2.3.2 for the user icon getting displayed directly with the elgg_view_entity_icon() function instead of some custom code. Only the border is added additionally to highlight friends and admins. I thought that was what you had suggested missing the suggestion about the ul list part (I've read the issue only after making the release to be honest). Only after reading I got the idea how the list code might be able to achieve. I'll give my idea a try (still working on a version for Elgg 3 right now and if it works I can make a new release also for Elgg 2.3).
